# SITE CONFIGURATION
title: Электромонтажные работы в Оренбурге и области. 
# your site title 

author: Sergey Vladimirovich # You :P
description: > # Meta description of Homepage
  Услуги электрика в Оренбурге, монтаж электропроводки в квартире, доме, офисе &amp;quot;под ключ&amp;quot;.
baseurl: "/" # the subpath of your site, e.g. /blog
keywords: 
  электрик оренбург, электрика +в оренбурге, прокладка кабеля, кабель прокладка, электромонтажные работы, выключатель подключение, проводка дом, электромонтаж, проводка +в доме, услуга электрик, услуги электрика, заземление частный дом, монтаж кабеля, кабель монтаж, электропроводка дом, электропроводка +в доме, электропроводка монтаж, дом электрик, проводка квартира, розетка установка, установка розеток, услуги электрика оренбург, установка выключателя, выключатель установка, электричество подключение, проводка цена, электропроводка квартира, сайт электрик, электрик +на дом, электрик цена, монтаж проводки, проводка монтаж, проводка замена, электромонтажные работы +в оренбурге, электромонтажные работы 2018, электрик вызывать, электропроводка замена, прайс +на электромонтажные работы, электромонтаж оренбург, электрик +на дом оренбург, авито оренбург электрика, розетка монтаж, электропроводка +в частном доме, электрик квартира, вызвать электрика оренбург, электромонтажные работы оренбург прайс, проводка +в частном доме, прокладка кабеля цена, частный электрик, расценки +на электромонтажные работы, прайс лист +на электромонтажные работы, электромонтажные работы оренбург прайс лист, выключатель замена, цены +на электромонтажные работы, электропроводка цена, производство электромонтажных работ, расценки электромонтажных работ оренбург, электромонтажные работы прайс лист 2018, проводка +в панельном доме, прайс +на электромонтажные работы 2018, установка одноклавишного выключателя, расценки +на электромонтажные работы 2018, розетка скрытой установки, монтаж электрики, электрик частный дом, электрик монтаж, провести проводку +в доме, проводка разводка, прокладка проводка, вызвать электрика +на дом, электрик вызов, электрик разводка, заземление комплект, разводка электрики, вызов электрика +на дом, вызов дом электрик, выполнение электромонтажных работ, вызвать электрика +на дом оренбург, прокладка силового кабеля, прокладка силовой кабель, электрик стоимость, подключение электричества +к дому, штробить проводку, монтаж проводки +в доме, расценки +на электромонтажные работы 2018 оренбург, электропроводка +в панельном доме, электропроводка разводка, авито услуги электрика, монтаж электропроводки +в доме, монтаж проводки +в частном доме, деревянный дом проводка, монтаж кабель канала, электрик +на дом +в, цены +на электромонтажные работы 2018, прайс лист электромонтажных работ 2018 оренбург, открытый монтаж кабеля, услуги +по прокладке кабелей, монтаж проводки цена, проводка +в деревянном доме, прокладка метра кабеля, прокладка кабеля +в помещении, стоимость электромонтажных работ, прокладка кабеля +в гофре, прейскурант +на электромонтажные работы, установка розеток +и выключателей, проводка электрик, услуги электрика цены, установка розеток цена, прокладка проводки +в доме, прокладка проводов +и кабелей, проводка +в монолитном доме, прокладка проводке +в доме, установка розеток 220в, прейскурант +на электромонтажные работы 2018, электрика дом цена, прейскурант цен +на электромонтажные работы, развести проводку +в доме, проводка +в доме цена, прейскурант цен +на электромонтажные работы 2018, проводка ввод +в дом, проложить проводку +в доме, разводка проводки +в доме, услуги электрика оренбург цены, установка розеток проводка, расценки +на электромонтажные работы 2018 год, развести проводку +в частном доме, электрик +на дом цены, установка розетки +для электроплиты, электрики вызов +на дом цены, проводка +в жилом доме, скрытый электромонтаж, услуги частного электрика, сайт электромонтаж, прайс цен +на электромонтажные работы, электрик новостройка, разводка электрики +в квартире, электромонтаж расценки, электромонтаж дом, сайт услуг электрика, проведение электромонтажных работ, монтаж электрики цена, электромонтаж 56, разводка электрики +в частном доме, кабель монтаж цена, замена проводки +в доме, монтаж кабеля цена, монтаж кабеля открытым способом, разводка электрики +в доме, монтаж открытой проводки, сколько стоит монтаж кабеля, услуги электрика прайс лист, электрик деревянный дом, прайс цен +на услуги электрика, деревянный дом электропроводка, электрик монтаж точка, прайс +на услуги электрика, электромонтаж цены, монтаж электропроводок кабелями, услуги электрика электромонтажные работы, проводка электрики +в частном доме, проводка электрики +в доме, делать проводку +в доме, услуги электрика расценки, заказать электрика, проводка электропроводки +в доме, монтаж электрики +в загородном доме, монтаж электрики +в доме, монтаж электрической проводки, электрик недорого оренбург, выезд электрика +на дом, услуги электрика +на дом, стоимость проводки +в доме, монтаж точки электрики цена, сделать электрику +в доме, услуги электрика частные объявления, сколько стоят услуги электрика, монтаж кабелей +по стенам, работы +по электромонтажу, электромонтаж проводки, электромонтаж установка, монтаж проводки +в квартире, стоимость электрики частного дома, прайс электромонтаж, разводка электрики +в однокомнатной квартире, проводка +в новостройке, частный электрик +на дом, электрик +на дом недорого, стоимость услуг электрика, услуги электрика +в квартире, услуги профессионального электрика, силовой кабель монтаж, поменять проводку +в доме, услуги квалифицированного электрика, электромонтаж +в квартире, сделать электрику +в частном доме, монтаж электрики расценки, монтаж электрики +в квартире, прейскурант услуг электрика, электрик квартира под ключ, электрик +на дом срочно, жилой дом +на электриков, электрик под ключ, электропроводка новостройка, электрика под ключ цена, электрика под ключ, электрик +на дом прайс, предлагаю услуги электрика, требуются услуги электрика, услуги ремонта квартир +по электрике, услуги электрика стоимость работ, услуги электрика замена проводки, оказание услуг электрика
url: "http://electromontage.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Сергей
  links:
    - https://vk.com/electromontage56
    - https://www.instagram.com/electromontage56/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Главная', link: '/'}
  - {name: 'Прайс', link: '/price'}
  - {name: 'Контакты', link: '/contact'}

tagline: >
  <h2>Быстро, качественно, недорого.</h1>  
  <h2 style="color:red">940-666</h2>

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: studenikhin.s@mail.ru # email for form submission

vk_username: electromontage56
instagram_username: electromontage56
mail_username: studenikhin.s@mail.ru 
# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']


compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

